[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dependabot-pyproject"
version = "0.1.dev0"
description = "A simple pyproject.toml file for testing dependabot"
license = "MIT"
authors = ["ANSYS, Inc. <ansys.support@ansys.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ansys-templates = "=0.3.0"
matplotlib = {version = "=3.5.1", optional = true}
pyvista = {version = "=0.35.1", optional = true}
pyside = {version = "=1.2.4", optional = true}

[tool.poetry.extras]
all = [
    "matplotlib",
    "pyvista",
    "pyside",
]
plotting = [
    "matplotlib",
    "pyvista",
]
qt = [
    "pyside",
]
